name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: 编译所有平台版本
        run: bash scripts/build.sh all

      - name: 创建 Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/rename_collection_linux_amd64
            build/rename_collection_linux_arm64
            build/rename_collection_windows_amd64.exe
            build/rename_collection_darwin_amd64
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}